language: python
python:
  - "2.7"
before_install:
 - sudo add-apt-repository -y ppa:pyside/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-pyside python-setuptools python-sphinx
 - export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages/"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3
install:
 - "pip install --requirement dev-requirements.txt"
 - "pip install --editable ."
script: python -m unittest discover src

